version: '2'
services:
  eurekaserver:
     image:   vy-ms/tmx-eurekasvr:assignment22
     ports:
         - "8761:8761"
  configserver:
      image: vy-ms/tmx-confsvr:assignment22
      ports:
         - "8888:8888"
      environment:
         EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
         EUREKASERVER_PORT: "8761"
         ENCRYPT_KEY:       "IMSYMMETRIC"
  database:
      image: postgres:9.5
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=p0stgr@s
        - POSTGRES_DB=eagle_eye_local
  assetsservice:
      image: vy-ms/tmx-assets-service:assignment22
      ports:
        - "8080:8080"
        - "8090:8090"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8080"
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        CONFIGSERVER_PORT:   "8888"
        DATABASESERVER_PORT: "5432"
        EUREKASERVER_PORT:   "8761"
        ENCRYPT_KEY:       "IMSYMMETRIC"
  organizationservice:
      image: vy-ms/tmx-organization-service:assignment22
      ports:
        - "8085:8085"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8085"
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        CONFIGSERVER_PORT:   "8888"
        DATABASESERVER_PORT: "5432"
        EUREKASERVER_PORT:   "8761"
        ENCRYPT_KEY:       "IMSYMMETRIC"
